# Generated by Django 4.1.1 on 2022-09-29 23:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("myapp", "0002_contributors_permission"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issues",
            name="assignee_user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignee_user_id",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
