# Generated by Django 4.1.1 on 2022-10-03 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_alter_issues_assignee_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contributors",
            name="permission",
            field=models.CharField(max_length=128, verbose_name="permission"),
        ),
    ]
